# Generated by Django 5.0.2 on 2024-02-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0002_complaintmodel_complaint_against_employeemodel_bedid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('BusId', models.AutoField(primary_key=True, serialize=False)),
                ('BusNumber', models.CharField(max_length=400)),
                ('NumberOfSeats', models.IntegerField()),
            ],
        ),
    ]
